import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

// Define the entity and its attributes
@Entity()
export class User {
  // nestjs pk generated by uuid
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // define column in table
  @Column({ unique: true })
  username: string;

  // define column in table
  @Column()
  password: string;
}
